sftp:
  hostname: <sfpt-hostname> ## SFTP server host or IP
  username: <sfpt-username> ## SFTP username
  password: <sfpt-password> ## SFTP password
  verify_host_key: false ## Wether to verify the SFTP host, set to true if possible

s3:
  bucket: <s3-bucket> ## bucket to place SFTP data
  key_prefix: <s3-key> ## key prefix for S3 destination files eg /sftp/original/file/path

## remove this section to use full sync
incremental_sync:
  last_modified_s3_key: sftp-sync-last-modified ## Key used for incremental sync
